server:
  port: 10007
spring:
  application:
    name: service-testb
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

  datasource:
    dynamic:
      master:
        driverClassName: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://rm-2zeefmb98v6f5qeuf.mysql.rds.aliyuncs.com:3306/ttjb-testb?useunicode=true&autoReconnect=true&tinyInt1isBit=false&allowMultiQueries=true
#        jdbc-url: jdbc:mysql://dev-a-mysql-live.ttjianbao.com:3306/treasure_mall?useunicode=true&autoReconnect=true&tinyInt1isBit=false&allowMultiQueries=true
        username: ttjb
        password: yjkj305!@#-db-test
      user:
        driver-class-name: com.mysql.jdbc.Driver
        jdbc-url: jdbc:mysql://dev-a-mysql-live.ttjianbao.com:3306/treasure_mall?useunicode=true&autoReconnect=true&tinyInt1isBit=false&allowMultiQueries=true
        username: ttjb
        password: yjkj305!@#-db-test
      primary: user
      druid:
        initial-size: 1
        max-active: 20
        min-idle: 1
        max-wait: 60000
    ###################以下为druid增加的配置###########################
#    type: com.alibaba.druid.pool.DruidDataSource

#总结一下，配置多数据源，大致需要三步：
#1.application.yml中添加多个数据源，如上所示，dynamic那一行是随意设置的，可以去掉
#2.configuration文件夹下面建立对应的config文件，可以不设定主数据源也不会报错
#3.每个数据源扫描对应的文件夹,创建Datasource、SqlSessionFactory(添加mapperLocations,用来扫描mapper)、TransactionManager、SqlSessionTemplate,